### PR TITLE
Unaligned references support fix

### LINKED ISSUE #220: Bebop on Rust - "reference to packed field is unaligned" - ENTIRE CRATE BROKEN ON LATEST RUST
**Describe the bug**
Using a unaligned references to packed fields seems to be an issue in the Rust compiler. It generates warnings or even a compile error.

**To Reproduce**
I used the following Bebop code:
```
struct IntVector {
    int32 x;
    int32 y;
}```
And it generated the following lines (among others):
```
    #[allow(unaligned_references)]
    fn _serialize_chained<W: ::std::io::Write>(&self, dest: &mut W) -> ::bebop::SeResult<usize> {
        Ok(self.x._serialize_chained(dest)? + self.y._serialize_chained(dest)?)
    }```
This generates the following warnings:
image

On the most recent nightly, the warnings turn into **hard errors**. This means using Bebop on Nightly is currently impossible.

**Expected behavior**
No compile issues.

**Bebop info:**
- Version: 2.4.9
- Runtime: Rust

**Desktop (please complete the following information):**
 - OS: Arch Linux

### PR DESCRIPTION
**Pull request by mattiecnvr**
WIP, just wanted to get something out there to track progress.

Fixes #220

### CODE REVIEW

File: Runtime/Rust/src/serialization/mod.rs [hunk 1]
```diff
@@ -391,38 +403,50 @@ where
...
             SliceWrapper::Raw(raw) => {
-                dest.write_all(&raw)?;
-                Ok(raw.len() + LEN_SIZE)
+                serialize_byte_slice(dest, raw)
             }
             SliceWrapper::Cooked(ary) => {
-                #[cfg(target_endian = "big")]
-                todo!();
-
-                let b: &[u8] = unsafe {
```
Comment (mattiecnvr) [inline Runtime/Rust/src/serialization/mod.rs:405]: I can't believe I forgot to account for padding. No one probably ran into this since the types are `#[repr(packed)]` but the code was technically invalid since nothing enforced a packed representation.

Comment (AndrewMD5) [reply Runtime/Rust/src/serialization/mod.rs:405]: Thanks for working on this 🖤

**Comment by mattiecnvr** [comment]
Also this seems to have not insignificantly speed up bebop sterilization
[criterion.zip](https://github.com/betwixt-labs/bebop/files/11012075/criterion.zip)

I tested this against the current master branch just now on my system and:

```
Jazz Library Serialization/Bebop
                        time:   [181.80 ns 182.23 ns 182.75 ns]
                        thrpt:  [3.1800 GiB/s 3.1891 GiB/s 3.1966 GiB/s]
                 change:
                        time:   [-15.445% -15.231% -15.003%] (p = 0.00 < 0.05)
                        thrpt:  [+17.651% +17.967% +18.267%]
                        Performance has improved.
```

**Review by AndrewMD5 — CHANGES_REQUESTED** [review]
I addressed the root cause of all integration test failing (see 23dc24c), however, when testing locally the Rust test all fail. Pull in the main fix and let's see if it resolves.

**Review by AndrewMD5 — APPROVED** [review]
Checks passing now. LGTM; thank you again.
